"""
Django settings for Weles project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR/'new_path'
BASE_DIR = Path(__file__).parent.resolve()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'no_key')

ENV = os.getenv('ENV', 'dev')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENV == 'dev'

ALLOWED_HOSTS = []

if not DEBUG:
    ALLOWED_HOSTS += ['127.0.0.1', 'localhost']

    domain = os.getenv('DOMAIN')
    if domain:
        ALLOWED_HOSTS.append(domain)

AUTH_USER_MODEL = 'users.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'crispy_forms',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',

    'weles.apps.users',
    'weles.apps.secrets'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'weles.apps.users.middleware.UserAgentMiddleware',
]

ROOT_URLCONF = 'weles.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR/'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'weles.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = str(BASE_DIR / 'static_collect')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    str(BASE_DIR / 'static'),
]

MEDIA_ROOT = str(BASE_DIR / 'media')
MEDIA_URL = '/media/'

#  ____            _     _             _   _
# |  _ \ ___  __ _(_)___| |_ _ __ __ _| |_(_) ___  _ __
# | |_) / _ \/ _` | / __| __| '__/ _` | __| |/ _ \| '_ \
# |  _ <  __/ (_| | \__ \ |_| | | (_| | |_| | (_) | | | |
# |_| \_\___|\__, |_|___/\__|_|  \__,_|\__|_|\___/|_| |_|
#            |___/

REGISTRATION_OPEN = True
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

#  ____      _                   _____
#  / ___|_ __(_)___ _ __  _   _  |  ___|__  _ __ _ __ ___  ___
# | |   | '__| / __| '_ \| | | | | |_ / _ \| '__| '_ ` _ \/ __|
# | |___| |  | \__ \ |_) | |_| | |  _| (_) | |  | | | | | \__ \
#  \____|_|  |_|___/ .__/ \__, | |_|  \___/|_|  |_| |_| |_|___/
#                  |_|    |___/
CRISPY_TEMPLATE_PACK = 'bootstrap4'

#  ____  _____ ____ _____   _____                                            _
# |  _ \| ____/ ___|_   _| |  ___| __ __ _ _ __ ___   _____      _____  _ __| | __
# | |_) |  _| \___ \ | |   | |_ | '__/ _` | '_ ` _ \ / _ \ \ /\ / / _ \| '__| |/ /
# |  _ <| |___ ___) || |   |  _|| | | (_| | | | | | |  __/\ V  V / (_) | |  |   <
# |_| \_\_____|____/ |_|   |_|  |_|  \__,_|_| |_| |_|\___| \_/\_/ \___/|_|  |_|\_\
#
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.BasicAuthentication'
    ),
}
