# Generated by Django 3.0.3 on 2020-02-16 19:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
