# Generated by Django 3.0.3 on 2020-02-16 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0002_secret_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secretaccesslog',
            name='secret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='secrets.Secret'),
        ),
    ]
