# Generated by Django 3.0.3 on 2020-02-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0003_auto_20200216_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretaccesslog',
            name='file',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secretaccesslog',
            name='url',
            field=models.IntegerField(default=0),
        ),
    ]
