# Generated by Django 3.0.3 on 2020-02-17 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secrets', '0004_auto_20200216_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretaccesslog',
            name='file',
        ),
        migrations.RemoveField(
            model_name='secretaccesslog',
            name='url',
        ),
    ]
